version: '2.1'
services:
  kafka:
    image: ubuntu/kafka:edge
    ports:
      - "9092:9092"
    environment:
      - "ZOOKEEPER_HOST=zookeeper"
      - "ZOOKEEPER_PORT=2181"
      - "TZ=UTC"
    networks:
      backend:
        aliases:
          - "kafka"
  zookeeper:
    image: ubuntu/zookeeper:edge
    ports:
      - "2181:2181"
    environment:
      - "TZ=UTC"
    networks:
      backend:
        aliases:
          - "zookeeper"

networks:
  backend:
    driver: bridge