spring-app:
  security:
    o-auth-2: true

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 631235605387-gptq556ui3mee77f1th6u0ej2jb04t7m.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
      resourceserver:
        jwt:
          issuer-uri: http://authserver:9000