spring:
  security:
    oauth2:
      client:
        provider:
          taco-resource:
            issuer-uri: http://authserver:9000
#          taco-resource-keycloak:
#            issuer-uri: http://localhost:18080/realms/spring-apps
        registration:
          taco-admin-client-oidc:
            provider: taco-resource
            client-name: Spring-Authorization
            client-id: taco-admin-client
            client-secret: taco-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - openid
#          taco-admin-client-keycloak:
#            provider: taco-resource-keycloak
#            client-name: Keycloak
#            client-id: spring-web-app.ui
#            client-secret: ${KEYCLOAK_REGISTRATION_CLIENT_SECRET}
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope:
#              - openid

spring-app:
  security:
    oauth2:
      oidc-service-configurer:
        taco-admin-client-oidc: cmahy.simple.spring.webapp.resource.impl.adapter.security.oidc.spring.service.TacoResourceSpringOidcServiceImpl
#        taco-admin-client-keycloak: cmahy.simple.spring.webapp.resource.impl.adapter.security.oidc.spring.service.TacoResourceSpringOidcServiceImpl