server:
  port: 8443
  ssl:
    enabled: true
    bundle: https

spring:
  ssl:
    bundle:
      jks:
        https:
          key:
            alias: https-server
          keystore:
            location: classpath:ssl/https-server.p12
            password: testtest
            type: PKCS12
        taco-external-resource:
          key:
            alias: https-server
          truststore:
            location: classpath:ssl/truststore-server.p12
            password: testtest
            type: PKCS12

application:
  taco:
    ingredients:
      external-resource:
        ssl:
          enabled: true
          bundle-name: taco-external-resource
        base-url: https://localhost:8443/api/v1

trust:
  store: classpath:keystore/baeldung.p12
  store-password: testtest