spring-app:
  security:
    oauth2:
      enable: true

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SIMPLE_SPRING_WEBAPP_GOOGLE_CLIENT_ID}
            client-secret: ${SIMPLE_SPRING_WEBAPP_GOOGLE_CLIENT_SECRET}
            scope: email, profile