spring:
  datasource:
    generate-unique-name: false
    url: jdbc:mysql://localhost:3306/webapp_resource_cloud?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: sa
    password: sa
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
