spring:
  application:
    name: ShellClient
  main:
    web-application-type: none
  config:
    import: classpath:messages/help-messages.yml
  output:
    ansi:
      enabled: always

application:
  console:
    output:
      format: "\n\r# --------------- @ --------------- @ --------------- #\n\r%s\n\r# --------------- @ --------------- @ --------------- #\n\r\n\r"
  taco-shop:
    webclient:
      enabled: true