application:
  web-client:
    common:
      connect-timeout: 5s
      response-timeout: 5s
      read-timeout: 5s
      write-timeout: 5s
    taco:
      credentials:
        username: machine2machine
        password: machine2machine
  taco:
    ingredients:
      external-resource:
        base-url: 'http://localhost:8080/api/v1'
        page-size: 5