services:
  cassandra:
    container_name: cassandra
    image: cassandra:latest
    ports:
      - '9042:9042'
    networks:
      backend:
        aliases:
          - "cassandra"

networks:
  backend:
    name: "cassandra-net"
    driver: bridge