server:
  port: 8090

spring:
  application:
    name: kafka-consumer
  kafka:
    consumer:
      bootstrap-servers:
        - localhost:9092
      group-id: 1
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      auto-offset-reset: earliest