version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      backend:
        aliases:
          - "rabbitmq"

networks:
  backend:
    driver: bridge