name: Run Taco Shop Resource package publisher

on:
  push:
    tags:
      - 'authorization/\d+/authorization-\d+\.\d+\.\d+'

jobs:
  publish:
    name: Publish Taco Shop Resource (${{github.ref_name}})

    runs-on: ubuntu-latest

    steps:

      - name: Checkout commit ${{github.sha}}
        uses: actions/checkout@v4

      - name: Publish API package
        if: startsWith(github.ref, 'refs/tags/authorization') && contains(github.ref, 'authorization')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/authorization
          github-token: ${{ secrets.GITHUB_TOKEN }}