name: Run Taco Shop Resource package publisher

on:
  push:
    tags:
      - 'taco-resource-api-\d+\.\d+\.\d+'
      - 'taco-resource-ui-\d+\.\d+\.\d+'
      - 'taco-resource-it-cassandra-\d+\.\d+\.\d+'
      - 'taco-resource-it-h2-\d+\.\d+\.\d+'
      - 'taco-resource-it-mysql-\d+\.\d+\.\d+'
      - 'taco-resource-impl-\d+\.\d+\.\d+'

jobs:
  publish:
    name: Publish Taco Shop Resource (${{github.ref_name}})

    runs-on: ubuntu-latest

    steps:

      - name: Checkout commit ${{github.sha}}
        uses: actions/checkout@v4

      - name: Publish API package
        if: startsWith(github.ref, 'refs/tags/taco-resource-api')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/resource/api
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish UI package
        if: startsWith(github.ref, 'refs/tags/taco-resource-ui')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/resource/ui
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish IT Cassandra package
        if: startsWith(github.ref, 'refs/tags/taco-resource-it-cassandra')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/resource/integration-test-persistence/cassandra
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish IT H2 package
        if: startsWith(github.ref, 'refs/tags/taco-resource-it-h2')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/resource/integration-test-persistence/h2
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish IT MySql package
        if: startsWith(github.ref, 'refs/tags/taco-resource-it-mysql')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/resource/integration-test-persistence/mysql
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Impl package
        if: startsWith(github.ref, 'refs/tags/taco-resource-impl')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/resource/impl
          github-token: ${{ secrets.GITHUB_TOKEN }}