name: Run Taco Shop Kernel package publisher

on:
  push:
    tags:
      - 'taco-shop/kernel/\d+/domain-\d+\.\d+\.\d+'
      - 'taco-shop/kernel/\d+/vo-\d+\.\d+\.\d+'
      - 'taco-shop/kernel/\d+/application-\d+\.\d+\.\d+'

jobs:
  publish:
    name: Publish Taco Shop Kernel (${{github.ref_name}})

    runs-on: ubuntu-latest

    steps:

      - name: Checkout commit ${{github.sha}}
        uses: actions/checkout@v4

      - name: Publish Domain package
        if: startsWith(github.ref, 'refs/tags/taco-shop/kernel') && contains(github.ref, 'domain')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/taco/shop/kernel/domain
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish VO package
        if: startsWith(github.ref, 'refs/tags/taco-shop/kernel') && contains(github.ref, 'vo')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/taco/shop/kernel/vo
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Application package
        if: startsWith(github.ref, 'refs/tags/taco-shop/kernel') && contains(github.ref, 'application')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/taco/shop/kernel/application
          github-token: ${{ secrets.GITHUB_TOKEN }}