name: Run User Adapter package publisher

on:
  push:
    tags:
      - 'user-adapter-repository-jpa-\d+\.\d+\.\d+'
      - 'user-adapter-repository-cassandra-\d+\.\d+\.\d+'
      - 'user-adapter-repository-webclient-\d+\.\d+\.\d+'

jobs:
  publish:
    name: Publish User Adapter (${{github.ref_name}})

    runs-on: ubuntu-latest

    steps:

      - name: Checkout commit ${{github.sha}}
        uses: actions/checkout@v4

      - name: Publish JPA repository package
        if: startsWith(github.ref, 'refs/tags/user-adapter-repository-jpa')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/user/adapter/repository/jpa
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Cassandra repository package
        if: startsWith(github.ref, 'refs/tags/user-adapter-repository-cassandra')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/user/adapter/repository/cassandra
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish WebClient repository package
        if: startsWith(github.ref, 'refs/tags/user-adapter-repository-webclient')
        uses: ./.github/workflows/publish
        with:
          working-directory: webapp/user/adapter/repository/webclient
          github-token: ${{ secrets.GITHUB_TOKEN }}